### ISSUE TITLE
Regression in 0.8: `jinja2.exceptions.TemplateNotFound: index.html.j2`

### ISSUE THREAD

**Issue by StanczakDominik** [danielfrg/jupyter-flex#103]
With these packages:

- nbconvert 6.2.0
- ipykernel 6.4.1
- Jinja2 3.0.2
- voila 0.2.16
- jupyter-flex 0.7.3

<details>
<summary>Additionally: output of `jupyter --version`</summary>

```
>>> jupyter --version
Selected Jupyter core packages...
IPython          : 7.28.0
ipykernel        : 6.4.1
ipywidgets       : 7.6.5
jupyter_client   : 6.1.12
jupyter_core     : 4.8.1
jupyter_server   : 1.11.1
jupyterlab       : 3.1.18
nbclient         : 0.5.4
nbconvert        : 6.2.0
nbformat         : 5.1.3
notebook         : 6.4.4
qtconsole        : not installed
traitlets        : 5.1.0
```

</details>

running `voila --template=flex Reproducer.ipynb` on [this simple notebook](https://gist.github.com/StanczakDominik/2a2ec0380d57e17424a84bda5a3e9962) runs without a hitch. With `jupyter-flex 0.8.0` (all other versions the same), however, I get:

```
[Voila] Using /tmp to store connection files
[Voila] Storing connection files in /tmp/voila_5x_t0xgi.
[Voila] Serving static files from /home/dominik/.local/lib/python3.9/site-packages/voila/static.
[Voila] Voilà is running at:
http://localhost:8866/
[Voila] WARNING | Notebook Reproducer.ipynb is not trusted
ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/dominik/.local/lib/python3.9/site-packages/voila/handler.py", line 163, in get
    async for html_snippet, resources in self.exporter.generate_from_notebook_node(notebook, resources=resources, extra_context=extra_context):
  File "/home/dominik/.local/lib/python3.9/site-packages/voila/exporter.py", line 100, in generate_from_notebook_node
    async for output in self.template.generate_async(nb=nb_copy, resources=resources, **extra_context, static_url=self.static_url):
  File "/home/dominik/.local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 148, in template
    self._template_cached = self._load_template()
  File "/home/dominik/.local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 359, in _load_template
    return self.environment.get_template(template_file)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib/python3.9/site-packages/jinja2/loaders.py", line 558, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: index.html.j2
ERROR:tornado.access:500 GET / (127.0.0.1) 597.95ms
```

Just thought I should probably report this! I'd be happy to help with reproducing/debugging in any way possible.

**Comment by danielfrg** [comment]
This changed in `0.8.0`, now you need to use the `jupyter-flex` command instead of `voila`.

```shell
jupyter-flex Reproducer.ipynb
```

I forgot to update the docs on this but its there now. Let me know if you find other issues!
