### ISSUE TITLE
Error with Traitlets 5.0

### ISSUE THREAD

**Issue by chaydenfowler** [danielfrg/jupyter-flex#54]
Would like to advise that this package appears to break with the most recent version of Traitlets (5.0.4), works with Traitlets (4.3.1) [minimum dependency w/ ipywidgets, haven't tested other versions]. Seems traitlets has a short history of not being fully backwards compatible (re: v4.1 and now v5.0)

Traitlets doesn't seem to be an explicit dependency for this package (?), but jupyter notebook breaks without it.

Console output on opening a notebook w/ jupyter-flex and traitlets 5.0.4

```[E 14:07:03.998 NotebookApp] Uncaught exception GET /notebooks/040b_MDD-Excel.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/040b_MDD-Excel.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\traitlets\traitlets.py", line 533, in get
    KeyError: 'template_path'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\tornado\gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\notebook\notebook\handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\notebook\base\handlers.py", line 512, in render_template
        return template.render(**ns)
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\jinja2\environment.py", line 1090, in render
        self.environment.handle_exception()
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\notebook\templates\notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\notebook\templates\page.html", line 154, in top-level template code
        {% block header %}
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\notebook\templates\notebook.html", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\notebook\notebook\handlers.py", line 42, in get_frontend_exporters
        exporter_instance = exporter_class()
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\jupyter_flex\exporter.py", line 94, in __init__
        self.environment.globals["dev_mode"] = DEV_MODE
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\nbconvert\exporters\templateexporter.py", line 126, in environment
        self._environment_cached = self._create_environment()
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\nbconvert\exporters\templateexporter.py", line 411, in _create_environment
        additional_paths + \
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\jupyter_flex\exporter.py", line 80, in template_path
        return super().template_path + [
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\traitlets\traitlets.py", line 573, in __get__
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\traitlets\traitlets.py", line 536, in get
      File "c:\users\chayd\documents\intertek\tempvenv\lib\site-packages\traitlets\traitlets.py", line 1572, in trait_defaults
    traitlets.traitlets.TraitError: 'template_path' is not a trait of 'FlexExporter' instances
```

**Comment by danielfrg** [comment]
Yes, currently we dont support new versions of trailtlets, nbconvert and voila. We are working on it here: https://github.com/danielfrg/jupyter-flex/pull/53

**Comment by chaydenfowler** [comment]
Wonderful. I'll close this issue then. Thank you for your hard work!
